// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pixel_clock_info.proto

#ifndef PROTOBUF_pixel_5fclock_5finfo_2eproto__INCLUDED
#define PROTOBUF_pixel_5fclock_5finfo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_pixel_5fclock_5finfo_2eproto();
void protobuf_AssignDesc_pixel_5fclock_5finfo_2eproto();
void protobuf_ShutdownFile_pixel_5fclock_5finfo_2eproto();

class PixelClockInfoBuffer;

// ===================================================================

class PixelClockInfoBuffer : public ::google::protobuf::Message {
 public:
  PixelClockInfoBuffer();
  virtual ~PixelClockInfoBuffer();
  
  PixelClockInfoBuffer(const PixelClockInfoBuffer& from);
  
  inline PixelClockInfoBuffer& operator=(const PixelClockInfoBuffer& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const PixelClockInfoBuffer& default_instance();
  
  void Swap(PixelClockInfoBuffer* other);
  
  // implements Message ----------------------------------------------
  
  PixelClockInfoBuffer* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PixelClockInfoBuffer& from);
  void MergeFrom(const PixelClockInfoBuffer& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 channel_id = 1;
  inline bool has_channel_id() const;
  inline void clear_channel_id();
  static const int kChannelIdFieldNumber = 1;
  inline ::google::protobuf::int32 channel_id() const;
  inline void set_channel_id(::google::protobuf::int32 value);
  
  // optional int64 time_stamp = 2;
  inline bool has_time_stamp() const;
  inline void clear_time_stamp();
  static const int kTimeStampFieldNumber = 2;
  inline ::google::protobuf::int64 time_stamp() const;
  inline void set_time_stamp(::google::protobuf::int64 value);
  
  // required int32 direction = 3;
  inline bool has_direction() const;
  inline void clear_direction();
  static const int kDirectionFieldNumber = 3;
  inline ::google::protobuf::int32 direction() const;
  inline void set_direction(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:PixelClockInfoBuffer)
 private:
  inline void set_has_channel_id();
  inline void clear_has_channel_id();
  inline void set_has_time_stamp();
  inline void clear_has_time_stamp();
  inline void set_has_direction();
  inline void clear_has_direction();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int64 time_stamp_;
  ::google::protobuf::int32 channel_id_;
  ::google::protobuf::int32 direction_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_pixel_5fclock_5finfo_2eproto();
  friend void protobuf_AssignDesc_pixel_5fclock_5finfo_2eproto();
  friend void protobuf_ShutdownFile_pixel_5fclock_5finfo_2eproto();
  
  void InitAsDefaultInstance();
  static PixelClockInfoBuffer* default_instance_;
};
// ===================================================================


// ===================================================================

// PixelClockInfoBuffer

// optional int32 channel_id = 1;
inline bool PixelClockInfoBuffer::has_channel_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PixelClockInfoBuffer::set_has_channel_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PixelClockInfoBuffer::clear_has_channel_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PixelClockInfoBuffer::clear_channel_id() {
  channel_id_ = 0;
  clear_has_channel_id();
}
inline ::google::protobuf::int32 PixelClockInfoBuffer::channel_id() const {
  return channel_id_;
}
inline void PixelClockInfoBuffer::set_channel_id(::google::protobuf::int32 value) {
  set_has_channel_id();
  channel_id_ = value;
}

// optional int64 time_stamp = 2;
inline bool PixelClockInfoBuffer::has_time_stamp() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PixelClockInfoBuffer::set_has_time_stamp() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PixelClockInfoBuffer::clear_has_time_stamp() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PixelClockInfoBuffer::clear_time_stamp() {
  time_stamp_ = GOOGLE_LONGLONG(0);
  clear_has_time_stamp();
}
inline ::google::protobuf::int64 PixelClockInfoBuffer::time_stamp() const {
  return time_stamp_;
}
inline void PixelClockInfoBuffer::set_time_stamp(::google::protobuf::int64 value) {
  set_has_time_stamp();
  time_stamp_ = value;
}

// required int32 direction = 3;
inline bool PixelClockInfoBuffer::has_direction() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PixelClockInfoBuffer::set_has_direction() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PixelClockInfoBuffer::clear_has_direction() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PixelClockInfoBuffer::clear_direction() {
  direction_ = 0;
  clear_has_direction();
}
inline ::google::protobuf::int32 PixelClockInfoBuffer::direction() const {
  return direction_;
}
inline void PixelClockInfoBuffer::set_direction(::google::protobuf::int32 value) {
  set_has_direction();
  direction_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_pixel_5fclock_5finfo_2eproto__INCLUDED
